### ISSUE TITLE
TIBCO Jaspersoft Studio 6.11.0 Stretch with overflow is gone？

### ISSUE THREAD

**Issue by tian2928** [TIBCOSoftware/jaspersoft-studio-ce#14]
TIBCO Jaspersoft Studio 6.11.0 ->Text Fields->Stretch with overflow is gone？
![image](https://user-images.githubusercontent.com/31798034/72224894-3d7cce00-35ba-11ea-99e8-55a048ee2f63.png)

**Comment by gt78** [comment]
Hi Tian, yes, the checkbox is no longer available, since Stretch with overflow is now part of the text adjust options:
- Cut Text (which is the default)
- Stretch Height (which is the same as the old stretch with overflow)
- Scale Font  (which instead of stretching the element, JasperReports will try to decrease the font size until the full text fit the textfield size).

Giulio

**Comment by tian2928** [comment]
Cool, thanks
