### ISSUE TITLE
JasperReport Studio 6.20.1 bug on Settings dialogs

### ISSUE THREAD

**Issue by richso** [TIBCOSoftware/jaspersoft-studio-ce#65]
using Jaspersoft Studio 6.20.1 under MacOS Ventura 13.2 (Apple M1)

when opening the dialog under Settings -> Jaspersoft Studio -> Fonts -> click the [Add] button, the window focused to the "Preferences" dialog and NOT the "Font Family" Dialog that caused no response to any actions, e.g. button click, typing text to the "Font Family" Dialog but "Preferences" Dialog. Only after pressing the ESC key to dismiss the "Preferences" dialog, the "Font Family" Dialog works.  HOWEVER, it's because the "Preferences" dialog closed previously, the font changes cannot be saved

![jasper](https://user-images.githubusercontent.com/5850283/233613926-b0c8a14b-4113-4ed7-b37a-c1b9658f49bf.png)

**Comment by richso** [comment]
On further testing, although the "Font Family" finally gain the input focus after closing the "Preferences" dialog, but changes to font settings cannot be saved by clicking the [Finish] button (no error message displayed)

**Comment by maxrabbi** [comment]
Thanks for reporting we will try to reproduce the scenario and fix it.

Regards,
Massimo.

**Comment by maxrabbi** [comment]
Hi, after some tests it appears that the problem is present only for Mac OS X. 
I've tested in a Windows 10 VM and a Linux Mint 21 VM: no issue verified. 

I assume there is some kind of platform specific bug when using the provided shell to create the WizardDialog instance.
I will try to apply a platform specific fix if I can not come up with a "cover-all" solution.

Regards,
Massimo.

**Comment by maxrabbi** [comment]
A fix will be available in the next official CE release.

Regards,
Massimo.
