### ISSUE TITLE
An error occurred when svn was selected as the repository

### ISSUE THREAD

**Issue by heyizhiyuan** [TIBCOSoftware/jaspersoft-studio-ce#73]
<img width="712" alt="image" src="https://github.com/TIBCOSoftware/jaspersoft-studio-ce/assets/39208129/2b7f0459-7f20-4e0b-9df3-a8618a2e9cc8">

studio version:  6.20.6

**Comment by maxrabbi** [comment]
Hi @heyizhiyuan I was suggesting to try manually installing the latest version. Currently for building purposes we are "forced" to use a signed old version of the Subclipse plugin.
But apparently the problem is something that came up with the latest versions of Eclipse. It seems starting from 2023-06 or 4.28.
It appears so, looking at some comments in the Marketplace page: https://marketplace.eclipse.org/content/subclipse 

I will monitor the situation since it seems something is not ok also in the most recent 2023-09 (last comment).

Regards,
Massimo.

**Comment by heyizhiyuan** [comment]
Thanks for reply! I had tried to install the latest version of Subclipse manually, and it does work now
